import { Captions, Volume2 } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "./ui/dialog";
import StringForm, { stringForm } from "@/forms/stringForm";
import { formatDateToTime } from "@/middlewere/uti";
import { Button } from "./ui/button";
import { Movie, ShowTime, SubTheatre } from "@/types";
import { useState } from "react";
import MovieSelectWidget from "./movieSelectWidget";
import ShowTimeForm, { showTimeForm } from "@/forms/showTimeForm";


type Props = {
    theatre: SubTheatre,
    index: number,
    onSave: (updatedTheatre: SubTheatre, index: number) => void,
    onCreateNewTheatre: (subTheatre: SubTheatre) => void
    onSaveApi: (index: number) => void
    movies: Movie[]
}

const EditTeatreCard = ({ theatre, index, movies, onSave, onSaveApi, onCreateNewTheatre }: Props) => {
    const [isEdit, setIsEdit] = useState<boolean>(false);

    const handleEditMovie = (movie: Movie) => {
        onSave({ ...theatre, movie: movie }, index);
        setIsEdit(true);
    }

    function repeatDigitsFromNumber(length: number): string {
        return '1'.repeat(length);
    }


    const handleEditShowTime = (showTime: showTimeForm) => {
        // Convert date to ISO string and then parse it back to Date
        const formattedDate = showTime.date.toISOString();
        console.log("Formatted Date:", formattedDate);

        // Create new ShowTime object
        const newShowTime: ShowTime = {
            _id: "new_id", // This should be unique or generated by the backend
            time: new Date(formattedDate), // Convert ISO string back to Date object
            seat: repeatDigitsFromNumber(showTime.seat), // Ensure this function formats the seat correctly
            subTheatre: theatre // Assuming `theatre` contains relevant details or an ID
        };

        console.log("New ShowTime Object:", newShowTime);

        // Update theatre with new show time
        const updatedTheatre = {
            ...theatre,
            showTime: [...theatre.showTime, newShowTime]
        };

        console.log("Updated Theatre Object:", updatedTheatre);

        // Save updated theatre
        onSave(updatedTheatre as SubTheatre, index);
        setIsEdit(true); // Indicate that editing is complete
    };
    return (
        <div key={index} className="flex flex-col w-full gap-3 bg-zinc-800 rounded-lg p-3">
            <div className="flex flex-row gap-1 text-lg justify-start items-center">
                <span className="font-medium">โรงภาพยนตร์ : </span>
                <div className="flex flex-row gap-3">
                    <span>{theatre.name}</span>
                    <span> |</span>
                    <div className="flex flex-row gap-2 justify-center items-center">
                        <Volume2 size={20} />
                        <span>ENG</span>
                    </div>
                    <span> |</span>
                    <div className="flex flex-row gap-2 justify-center items-center">
                        <Captions size={20} />
                        <span>TH</span>
                    </div>
                </div>
                <Dialog>
                    <DialogTrigger className="bg-yellow-500 hover:bg-yellow-400 p-2 rounded-md ">
                        <span className="text-sm font-bold text-zinc-800">เเก้ใข</span>
                    </DialogTrigger>
                    <DialogContent className="w-full">
                        <StringForm
                            currentMovie={{ name: theatre.name }}
                            onSave={(data: stringForm) => {
                                onSave({ ...theatre, name: data.name }, index);
                                setIsEdit(true);
                            }}
                            isLoading={false}
                        />
                    </DialogContent>
                </Dialog>
            </div>
            <div className="flex flex-row gap-2 text-lg justify-start items-center">
                <span className="font-medium">ภาพยนตร์ : </span>
                <div className="flex flex-row gap-3">
                    <span>{theatre.movie.name}</span>
                </div>
                <Dialog >
                    <DialogTrigger className="bg-yellow-500 hover:bg-yellow-400 p-2 rounded-md ">
                        <span className="text-sm font-bold text-zinc-800">เเก้ใข</span>
                    </DialogTrigger>
                    <DialogContent className="h-full overflow-auto py-12">
                        <MovieSelectWidget movies={movies} onSave={handleEditMovie} />
                    </DialogContent>
                </Dialog>
            </div>
            <div className="flex flex-row w-full  justify-start items-start gap-2">
                <div className="flex gap-2 justify-center items-center">
                    <span className="font-medium text-center ">รอบฉาย : </span>
                    <Dialog>
                        <DialogTrigger className="bg-yellow-500 hover:bg-yellow-400 p-2 rounded-md ">
                            <span className="text-sm font-bold  text-zinc-800">เพิ่มรอบฉาย</span>
                        </DialogTrigger>
                        <DialogContent className="w-full  overflow-auto">
                            {/* <ShowTimeForm currentMovie={{
                                seat: 120,
                                date: new Date()
                            }} onSave={(data: showTimeForm) => {
                                console.log("add showtime");
                                handleEditShowTime(data);
                            }} isLoading={false}></ShowTimeForm> */}
                            อยู่ระหว่างการพัฒนา
                        </DialogContent>
                    </Dialog>
                </div>
                <div className="grid grid-cols-6 gap-1 text-lg">
                    {theatre.showTime.map((showTime, index) => (
                        <Button className="bg-gray-400 text-gray-200" key={index}>{formatDateToTime(showTime.time.toString())}</Button>
                    ))}
                </div>
            </div>
            {isEdit && <Button onClick={() => {
                if (!theatre._id) {
                    onCreateNewTheatre(theatre);
                } else {
                    onSaveApi(index);
                }

            }} className="bg-green-500">บันทึกการเปลี่ยนแปลง</Button>}
        </div>
    );
}

export default EditTeatreCard;
